### ISSUE TITLE
Is this "fake" or can this actually open a websocket?

### ISSUE THREAD

**Issue by Zireael07** [ThomasGysemans/BashInGodot#1]

**Comment by ThomasGysemans** [comment]
it's not fake, it just simulates the basics of Bash such as "echo", "cat", "chmod", "mkdir" etc as a plugin you can use in your own games.

It will also come with a simplified Assembler language called "M99".

It is a work-in-progress school project that I will make open-source and available on a website once it's finished.

edit : and no websocket, sorry
